---
- name: Brick test
  hosts: all
  remote_user: root
  tasks:
    - name: User creation
      ansible.builtin.user: 
        name: brickdev
        password: pass
        update_password: on_create

    - name: SSH directory verification
      ansible.builtin.file:  
        path: /home/brickdev/.ssh
        state: directory
        owner: brickdev
        group: brickdev
        mode: "0700"

    - name: Allow ssh key authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PubkeyAuthentication"
        line: "PubkeyAuthentication yes"

    - name: Add ssh key
      ansible.builtin.authorized_key:
        key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDW1sg+ys6EEZd6ZzbDlrMMybOBUALEtERY2/ZKsvgbcAzTERxbtsqu+iNNDBo+sf3L3YuWkd8fLH4SJ3MQV42ySc6ml2tMT0G2r+QIWwFz+nPaD2DY8blgFpsa41TZxwKgLmqEtUVlps9Q6Un5KtJMjTl2MWYKswdxSqHw8em0DNigJolWfzsmoTvd1HXTYdj/PiJECW3nS38PFlL19Av6ipwrbxme2/VyvjolX5F3p/dgLkuUU7UMQ+tlx9gAlN0F/Tf6zMHSubIBC7lOf58zP+IlykdD4leVaNpFckk9hxnKCZpyM7jlwi2YSnYLAOh4v56NTq7c/yG2jX9+lSb
        user: brickdev
        path: /home/brickdev/.ssh/authorized_keys

    - name: Root authentication prohibition
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PermitRootLogin"
        line: "PermitRootLogin no"

    - name: SSH daemon restart
      ansible.builtin.service:
        name: sshd
        enabled: true
        state: restarted 