---
- name: Brick test
  hosts: all
  remote_user: root
  tasks:
    - name: User creation
      ansible.builtin.shell: | 
        useradd brickdev -p pass -m
        echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config.d/updated.conf
        echo "PermitRootLogin no" >> /etc/ssh/sshd_config.d/updated.conf
        mkdir /home/brickdev/.ssh
        echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDW1sg+ys6EEZd6ZzbDlrMMybOBUALEtERY2/ZKsvgbcAzTERxbtsqu+iNNDBo+sf3L3YuWkd8fLH4SJ3MQV42ySc6ml2tMT0G2r+QIWwFz+nPaD2DY8blgFpsa41TZxwKgLmqEtUVlps9Q6Un5KtJMjTl2MWYKswdxSqHw8em0DNigJolWfzsmoTvd1HXTYdj/PiJECW3nS38PFlL19Av6ipwrbxme2/VyvjolX5F3p/dgLkuUU7UMQ+tlx9gAlN0F/Tf6zMHSubIBC7lOf58zP+IlykdD4leVaNpFckk9hxnKCZpyM7jlwi2YSnYLAOh4v56NTq7c/yG2jX9+lSb" > /home/brickdev/.ssh/authorized_keys
        